### ISSUE TITLE
Add matplotlib dependency to environment.yml

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#10]
Got error when importing `markers` from `dynamo` saying that there's no module named `mpl_toolkits`. You might want to include matplotlib as a dependency in the environment file. 

Importing matplotlib fixes this issue.

**Comment by alcantarar** [comment]
part of https://github.com/openjournals/joss-reviews/issues/1466

**Comment by abhishektha** [comment]
removed the matplotlib import as matplotlib wasn't used in `markers`.
