### ISSUE TITLE
[REVIEW] Error running test scripts

### ISSUE THREAD

**Issue by melund** [anderson-cu-bioastronautics/dynamo_realsense-capture#3]
I have the environment setup and dynamo installed. I am not sure I can run the test scripts without the actual physical hardware. But I tried anyway and got an error. I doubt it due to the missing camera though. 

```
(dynamo-review) C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_scripts>python testscript.py
Traceback (most recent call last):
  File "testscript.py", line 12, in <module>
    cameraFiles = os.listdir('dynamo/sample_files')
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dynamo/sample_files'
```

**Comment by abhishektha** [comment]
Hi @melund ,

Would you mind trying this again with the new testscript.py which I uploaded 2 days ago? I had noticed this error yesterday, where I had missed changing the local reference to the sample files. I believe the newest version of this file should be able to find the sample files (which replicate having a camera connected to the system) in the repository. You should be able to run the testscript without cameras connected as the sample files are read in as virtual cameras. 

You will also need the "pptk" package (from pip) installed to view the sample data from testscript.py

Thanks!
Abhi

**Comment by melund** [comment]
@abhishektha. Thanks. Now the script runs. I got the following output and some figures.  
```
$ python testscript.py
0 devices have been found
C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_files\20190418_142057.bag  sees the chessboard!
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x0ffffffff80010106)"
C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_files\20190418_142125.bag  sees the chessboard!
C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_files\20190418_142138.bag  sees the chessboard!
C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_files\20190418_142205.bag  sees the chessboard!
C:\Users\mel\Documents\GitRepositories\dynamo_realsense-capture\sample_files\20190418_142217.bag  sees the chessboard!
``` 

I guess that is expected when I don't have the cameras.
