### ISSUE TITLE
[REVIEW] Add community guidelines

### ISSUE THREAD

**Issue by melund** [anderson-cu-bioastronautics/dynamo_realsense-capture#4]
JOSS requires that there should be clear guidelines on how to contribute:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by abhishektha** [comment]
Community guidelines have now been added to the main README.md, please let me know if they need any further explanation or information!

**Comment by melund** [comment]
@abhishektha Looks good to me.
