### ISSUE TITLE
missing parameter in calibration.detectChessboard()

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#5]
Line 110 in calibration.py is throwing a TypeError suggesting that argument `chessboardSquareSize` is missing. However, this is occurring because `detectChessboard()` is missing the `cameraSet` argument. I have 2 cameras connected, how do I generate a list of their serial numbers?

**Comment by alcantarar** [comment]
linking to JOSS review  https://github.com/openjournals/joss-reviews/issues/1466

**Comment by abhishektha** [comment]
Hi @alcantarar , 

I just updated calibration.py to self-population the camera serial numbers when using calibration.new(), so try just running calibration.new() with its parameters and let me know if it doesn't work; it seems to work for me after this update.

**Comment by alcantarar** [comment]
Fix worked, thanks!
