### ISSUE TITLE
stream.py function documentation out of date

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#6]
[Example Tutorial documentation](https://github.com/anderson-cu-bioastronautics/dynamo_realsense-capture/blob/dynamo-release/examples/examples.md#camera-streaming-to-disk) gives this example:  
`stream.start(deviceManager, transformationMatrices, 'saveFolder', iteration, time)
`  

but `stream.start()` only takes in 4 arguments:  
`def start(deviceManager, deviceTransformations, saveDirectory, stream_time):
`  

Documentation in `stream.start()` matches Example Tutorial documentation, but not actual function design. I suggest going through function documentation and checking that number of arguments and argument names match. Outdated documentation persists in `stream.processThread()` and  `stream.captureThread()`, for example.

 Part of https://github.com/openjournals/joss-reviews/issues/1466

**Comment by abhishektha** [comment]
I've removed the outdated iteration argument from stream.start() and its references in all the documentation. This should now be updated in both the example tutorial documentation and the API documentation.

**Comment by abhishektha** [comment]
fixed by commit b972b86e91089126761db5548977be4226738cef

**Comment by alcantarar** [comment]
Including this because it's partof the same [Camera Streaming to Disk Tutorial](https://github.com/anderson-cu-bioastronautics/dynamo_realsense-capture/blob/dynamo-release/examples/examples.md#camera-streaming-to-disk), but it has a typo: `import pyrealsense 2 as rs`. should be `import pyrealsense2 as rs`

**Comment by alcantarar** [comment]
[Example Tutorial for Viewing Pointclouds](https://github.com/anderson-cu-bioastronautics/dynamo_realsense-capture/blob/dynamo-release/examples/examples.md#pointcloud-viewing-from-saved-frames) code has unused parameter `iteration` and misspelled function `viewPointClouds()`

**Comment by abhishektha** [comment]
closing after reviewing documentation
