### ISSUE TITLE
stream.captureThread() has camera serial number hardcoded

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#7]
lines 36 and 39 in `stream.py` throw KeyErrors because camera serial number `822512060853` is hardcoded. Replacing with my camera number fixes error. See lines 36-39 below:  

```
 fnumber = deviceManager.poll_frames()['822512060853'].get_frame_number() #get frame number to ensure subsequent frames are saved
    while i<int(90*stream_time):
        frames = deviceManager.poll_frames()
        newfnumber = frames['822512060853'].get_frame_number()
```

**Comment by alcantarar** [comment]
Part of https://github.com/openjournals/joss-reviews/issues/1466

**Comment by abhishektha** [comment]
`stream.py` now grabs the first enabled camera's serial number instead of hard-coding a serial number. This should fix this error!

**Comment by abhishektha** [comment]
commit b972b86e91089126761db5548977be4226738cef
