### ISSUE TITLE
calibration.load() loading newCalibration.cal as NoneType

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#8]
Running `stream.processThread()` using the transformation matrices generated from `calibration.new()` works, but using the transformation matrices from `calibration.load()` doesn't. No error is thrown during pickling/loading, but `transformationMatrices` is NoneType and causes `stream.py` to break at line 92: `deviceData['poseMat'] = devicesTransformation[device][0] #save transformation matrix
`

code I'm executing to create calibration file and load it:  
 ```
transformationMatrices = calibration.new(fileName, deviceManager, chessboardWidth, chessboardHeight, chessboardSquareSize) #Works (transformationMatrices = {dict})
transformationMatrices = calibration.load('newCalibration.cal') #Loads, but breaks stream.processThread() (transformationMatrices = {NoneType})
```
There may be an issue with how it's being pickled/loaded.

**Comment by alcantarar** [comment]
Part of https://github.com/openjournals/joss-reviews/issues/1466

**Comment by abhishektha** [comment]
The return parameter in calibration.load() was missing so it wasn't returning the loaded matrices. Should be fixed now!

**Comment by abhishektha** [comment]
commit 0c71c0c6cf4cbc765436bdbb3e6228e743771cd5
