### ISSUE TITLE
"RuntimeError: Camera already streaming" when trying to view pointclouds

### ISSUE THREAD

**Issue by alcantarar** [anderson-cu-bioastronautics/dynamo_realsense-capture#9]
When I run:  
`view.viewPointClouds(folder,full=0)`  

I get `RunTimeError: Camera already streaming` and print statements that say 2 devices have been found. The 3D interactive window pops up, but this RunTimeError is thrown repeatedly until I force stop the code. Ran in debug mode and it's breaking in `realsense_device_manager.enable_device()`.   Here's the full error:

```
2 devices have been found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dynamo-env\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "dynamo-env\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "dynamo-env\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "dynamo-env\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "dynamo-env\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "dynamo-env\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "dynamo-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "dynamo_realsense-capture\RA_Review.py", line 14, in <module>
    deviceManager.enable_all_devices()
  File "dynamo_realsense-capture\dynamo\realsense_device_manager.py", line 193, in enable_all_devices
    self.enable_device(serial, enable_ir_emitter)
  File "dynamo_realsense-capture\dynamo\realsense_device_manager.py", line 162, in enable_device
    pipeline_profile = pipeline.start(self._config)
RuntimeError: Camera already streaming
```

Again, the code keeps running but this error is thrown repeatedly.

**Comment by abhishektha** [comment]
@alcantarar I'm unable to reproduce this. Are you trying to run `realsense_device_manager.enable_all_devices()` in a loop? This  error is usually seen when you are trying to enable the camera once it is already enabled. You should only need to enable the camera once per session. 

I did just push an update (06a139dc55d2a85554b9abfe478c644ac4bc3b82) to `view.py` that should solve another bug I just found, don't think that would affect this issue but just wanted to let you know.

**Comment by alcantarar** [comment]
@abhishektha I forked the repository and have added the pickled frames from `stream.start()` [here](https://github.com/alcantarar/dynamo_realsense-capture/tree/dynamo-release/TEST_DATA) and my implementation of  `view.viewPointClouds()` [here](https://github.com/alcantarar/dynamo_realsense-capture/blob/dynamo-release/RA_Review.py). That's all I can do right now to help with reproducing the error since I won't be back with the cameras until later this week. 

(Part of https://github.com/openjournals/joss-reviews/issues/1466)

**Comment by abhishektha** [comment]
Thanks for doing that, I'll investigate and get back to you ASAP!

**Comment by abhishektha** [comment]
@alcantarar Still unable to recreate with your script nor files. If possible, would you mind testing if you can view your sample data with a new script where you simply try viewing the data?

**Comment by alcantarar** [comment]
@abhishektha I tried just running the following
```
view.viewPointClouds('C:/path/to/TEST_DATA', 0)
```
and get errors in `view.depthFrametoPC`:
```
    if not kwargs['format'] or kwargs['format'] == 'pcl':    
KeyError: 'format'

The above exception was the direct cause of the following exception:
 File "\dynamo_realsense-capture\dynamo\view.py", line 149, in viewPointClouds
    cameraPoints = p.map(depthFrametoPC, listP) #process point cloud for each camera in a separate thread
  File "\envs\dynamo-env\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "\envs\dynamo-env\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
KeyError: 'format'
```

**Comment by abhishektha** [comment]
@alcantarar, can you try the latest version of the code. commit 06a139dc55d2a85554b9abfe478c644ac4bc3b82 from a couple weeks ago should have addressed this problem and removed the reference to kwargs in the if statement

**Comment by alcantarar** [comment]
Shoot, I missed that you'd made that commit. It works as intended now.
